### ISSUE TITLE
Translation does not work on first load

### ISSUE THREAD

**Issue by Michal-MK** [AirLancer/ffs_msdn_in_english#5]
Hi, for about a week now the webpages stopped being translated on initial load.
(refreshing the page translates it.)
I assumed that the most recent update addressed the issue, but after updating and subsequntly completely reinstalling. The issue presists.

Chrome version: 72.0.3626.119 (Official build) (64bit) (cohort: Stable)
OS: Windows 10

Thanks

**Comment by AirLancer** [comment]
Sorry for the late reply. This has been on my ToDo list forever. But it seems the issue appeared and disappeared on its own.
Back when you reported it I could reproduce it, but I can't anymore.
Is it still present for you @Michal-MK ?

**Comment by Michal-MK** [comment]
I have since switched to a different addon, but I tried it now and it seems to be working again. (Sorry for being late aswell ;))

**Comment by AirLancer** [comment]
Thanks for the reply though :)
