### ISSUE TITLE
Add MDN support

### ISSUE THREAD

**Issue by daniel-zazula** [AirLancer/ffs_msdn_in_english#7]
Please add support for the MDN website as well:
https://developer.mozilla.org/

**Comment by AirLancer** [comment]
Hi,
this extension is focused on Microsoft pages. I try to keep it simple and to the point.
If you want something more configurable maybe the Redirector is for you:
https://addons.mozilla.org/en-US/firefox/addon/redirector/

Otherwise, feel free to fork this code and tweak it as you wish ;).
