### ISSUE TITLE
docs.microsoft.com is now learn.microsoft.com

### ISSUE THREAD

**Issue by Weishaupt** [AirLancer/ffs_msdn_in_english#9]
In its ongoing quest to confuse users, Microsoft keeps changing names left and right. This time https://docs.microsoft.com now redirects to https://learn.microsoft.com. This breaks the add-in behaviour.

**Comment by Weishaupt** [comment]
- Proposal for Chrome: #10 
- Proposal for Firefox: #11

**Comment by kipusoep** [comment]
Anyone there?

![Alt Text](https://media.giphy.com/media/d8lUKXD00IXSw/giphy.gif)

**Comment by kipusoep** [comment]
I'm now using the plugin and instruction from this post instead: https://stackoverflow.com/a/15392860/510149
So you can manage the redirects yourself and no need to rely on someone else to update a plugin.
